version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jjtirado/practica2:ej2
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    environment:
      - REDIS_HOST=redis
    ports:
      - "4000:4567"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6378:6378"   
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
